### ISSUE TITLE
Unable to use set_password with Windows stemcells

### ISSUE THREAD

**Issue by chomipi-zz** [cloudfoundry-incubator/windows-utilities-release#7]
Attempting to use the set_password job to create an additional admin user for vulnerability scanning. When deploying addon with set_password job against PCF Runtime for Windows v1.12.6 with light-bosh-stemcell-1200.13-azure-hyperv-windows2012R2, getting the below error:

Task 94271
 
Task 94271 | 18:24:14 | Preparing deployment: Preparing deployment (00:00:01)
                      L Error: Colocated job 'set_password' is already added to the instance group 'windows_diego_cell'.
Task 94271 | 18:24:15 | Error: Colocated job 'set_password' is already added to the instance group 'windows_diego_cell'.
 
Task 94271 Started  Mon Mar  5 18:24:14 UTC 2018
Task 94271 Finished Mon Mar  5 18:24:15 UTC 2018
Task 94271 Duration 00:00:01
Task 94271 error

**Comment by xtreme-sameer-vohra** [comment]
Hi @chomipi 
BOSH only allows a single instance of a job per instance group for integrity and consistency.
The set_password job currently only supports configuring a single user, which is meant to be used for the Administrator for debugging purposes. 

We can consider adding support for multiple users as a feature request that our team will look into.

**Comment by chomipi** [comment]
@xtreme-sameer-vohra we forked the release and made a copy of the set_password job (called it create_user) to create another admin user.
Would be nice to have a supported job that can create multiple/new users.

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the update @chomipi 

To confirm, the new user you create for scanning is also an admin ? What attributes do you set for this user (eg. What group(s) does the user belong to ?

**Comment by chomipi** [comment]
Yes also an admin. Added to Administrators group.
